// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApBIhhw2CtrtMU4-v3MQjdzQjkz84iEjc',
    appId: '1:37171104548:web:0fdfd606eba90bd3bf01b1',
    messagingSenderId: '37171104548',
    projectId: 'pertemuan10-c297b',
    authDomain: 'pertemuan10-c297b.firebaseapp.com',
    storageBucket: 'pertemuan10-c297b.firebasestorage.app',
    measurementId: 'G-DDEEN1H6S0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0y56k6weO06voFO0xsdqhuflgnJviZE',
    appId: '1:37171104548:android:7620900b1b8c683bbf01b1',
    messagingSenderId: '37171104548',
    projectId: 'pertemuan10-c297b',
    storageBucket: 'pertemuan10-c297b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKy8kvNcLMeHn1vJhnT9V8qVO2rt1Sfhs',
    appId: '1:37171104548:ios:54eada9fca66d368bf01b1',
    messagingSenderId: '37171104548',
    projectId: 'pertemuan10-c297b',
    storageBucket: 'pertemuan10-c297b.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKy8kvNcLMeHn1vJhnT9V8qVO2rt1Sfhs',
    appId: '1:37171104548:ios:54eada9fca66d368bf01b1',
    messagingSenderId: '37171104548',
    projectId: 'pertemuan10-c297b',
    storageBucket: 'pertemuan10-c297b.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApBIhhw2CtrtMU4-v3MQjdzQjkz84iEjc',
    appId: '1:37171104548:web:67cb7bfcc1f23303bf01b1',
    messagingSenderId: '37171104548',
    projectId: 'pertemuan10-c297b',
    authDomain: 'pertemuan10-c297b.firebaseapp.com',
    storageBucket: 'pertemuan10-c297b.firebasestorage.app',
    measurementId: 'G-8P9SCELXW6',
  );
}
